### ISSUE TITLE
Double taskbar icon after a update

### ISSUE THREAD

**Issue by kleqing** [CollapseLauncher/Collapse#142]
For those people always love pin a application. There is a problem with the application after the update. The app icon will be duplicate after a update. 

| Before update | After update |
| :-----------------: | :----------------: |
| ![image](https://github.com/neon-nyan/Collapse/assets/78801337/ded330c8-0572-47e0-91c2-34b573eebde5) | ![image](https://github.com/neon-nyan/Collapse/assets/78801337/a20b9cc1-590d-477b-af07-b2d887ff0fbd) |

# How to fix?

1. Temporary way
- Unpin and pin the application for each update.

2. Another way (I did not test yet)

- I found many things in the Internet and I found a ways to fix it. 
- First of all is create a batch file which will remove the old taskbar icon and add a new one but seem like it is impossible because there are no shortcut after a update. So [CSHarpLib](https://github.com/Ferrell-Technology/CSharpLib/wiki) which can create a temporary shortcut and then move it to ``%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`` is a way to fix it.

If the update are using InnoSetup to update the application for each new version, I think I can do something to help this project.

**Comment by bagusnl** [comment]
Try to make sure the shortcut you made to Collapse is to the executable on the root of the installation folder for Collapse, not the one inside the `app-x.x.x` folder.
What I usually do is to pin them to start menu first then from the icon on start menu, pin them to task bar. Seems to work fine for me so far after the Squirrell implementation.

**Comment by kleqing** [comment]
The Collapse shortcut always execute from the root directory. I also pin it to taskbar from star menu. Even the target is on `Collapse Launcher` folder. But the problem still exist!

**Comment by bagusnl** [comment]
It's quite weird, this is how my shortcut looks like:
![image](https://github.com/neon-nyan/Collapse/assets/28079733/5c6e80b1-e9af-4160-be9c-6382cdfd453c)
My current env:
- Windows 11 Insider Beta
- Collapse Preview 1.70.4

**Comment by kleqing** [comment]
![image](https://github.com/neon-nyan/Collapse/assets/78801337/690c0b2d-e7b7-4027-af89-c7ddec977c0e)

Same with you too

- Windows 10 build 19041
- Collapse Preview 1.70.04

But idk what happend to me. But last month I also have a same issues too on Windows 11

**Comment by bagusnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Double Taskbar icon after update](https://trello.com/c/Abtxh6Xr/8-double-taskbar-icon-after-update)

**Comment by Cryotechnic** [comment]
Potential cause may have been identified. We currently believe that this is because the application is not signed, which causes the app signature to change on every publish. 

Self-signing, and potentially getting an OV (Organization Verified) certification in the long term may remediate the issue by having the application signature remain fixed and distributed through a trust certificate bundled with Collapse during its initial installation.

We'll keep this issue open and update it as we implement this into the launcher. This is currently planned for the 1.72+ release lifecycle. 

Currently, the only way to remediate this issue is to unpin & re-pin the launcher. We apologize for any inconvenience we may have caused.

**Comment by bagusnl** [comment]
Ref 

https://github.com/ppy/osu/pull/28743

**Comment by Cryotechnic** [comment]
Fixed since 1.82.0
