### ISSUE TITLE
[Bug]: 4 pages are stacked on top

### ISSUE THREAD

**Issue by shikukuya** [CollapseLauncher/Collapse#272]
### Affected Version

1.71.9-PRE

### Bug Behavior

The four pages are stacked on top of each other and the error message page is transparent.

### Expected Behavior

Display only one page at a time

### Steps to reproduce

1. update metadata after 5 seconds
2. update game within 5 seconds
3. error updating game
4. :(

### Screenshot(s)

![image](https://github.com/neon-nyan/Collapse/assets/89395757/19018ad8-40dd-4184-9a2f-62352bad0672)

### Additional Information

[DxDiag.txt](https://github.com/neon-nyan/Collapse/files/12708117/DxDiag.txt)
[CollapseLog.txt](https://github.com/neon-nyan/Collapse/files/12708119/CollapseLog.txt)

**Comment by shikukuya** [comment]
I clicked the back button, then launcher crashes

**Comment by bagusnl** [comment]
For the game update error you can try manually downloading this file and put it on your yuanshen installation folder https://autopatchhk.yuanshen.com/client_app/update/hk4e_global/10/zh-cn_4.0.0_4.0.1_hdiff_yx71braIALoB502f.zip 
That bug should be fixed with latest commit but its not shipped yet

For the COMException one, you can try forcefully updating the launcher by downloading the latest portable preview in Releases page of this project and see if the problem persist

**Comment by bagusnl** [comment]
Also it seems that your connection to Bitbucket CDN is not good, you can try switching to Cloudflare CDN in the app settings page. Let us know if you still have problems

**Comment by bagusnl** [comment]
Fix for both small file download and COMException has been pushed to Preview, closing this issue. Shall same issue or similar appears please open a new issue ticket.

Thank you for using Collapse Launcher!
