### ISSUE TITLE
[Request]: Disable "Change Game" Warning

### ISSUE THREAD

**Issue by MetaSquared** [CollapseLauncher/Collapse#297]
### Is your request related to a problem?

No

### Describe your proposed solution

希望在切换游戏时不需要经过确认

### Describe alternatives you've considered

现在切换游戏时要点击一次更改，然后点击一次确认，这是不必要的操作。希望可以改为选择对应选项直接更改无需点击更改按钮和确认。

**Comment by muscularcandy67** [comment]
I admit I had to use Google Translate to understand what you said, and if I got it right your problem is the Change Game button warning appearing after selecting another game/region. There is actually a way already to disable this in Collapse Settings, therefore I'm going to close this as resolved already.
(Side note: Please write your issues in English)

**Comment by MetaSquared** [comment]
Thanks to the translator.
After turning off the server switch warning, I also hope to be able to switch directly in the menu bar by clicking on the corresponding game name or server without using the 'Change' button.

**Comment by MetaSquared** [comment]
> I admit I had to use Google Translate to understand what you said, and if I got it right your problem is the Change Game button warning appearing after selecting another game/region. There is actually a way already to disable this in Collapse Settings, therefore I'm going to close this as resolved already. (Side note: Please write your issues in English)

Thanks to the translator.
After turning off the server switch warning, I also hope to be able to switch directly in the menu bar by clicking on the corresponding game name or server without using the 'Change' button.
