### ISSUE TITLE
[Request]: Storage for download Genshin Impact in PC

### ISSUE THREAD

**Issue by Hekkal** [CollapseLauncher/Collapse#299]
### Is your request related to a problem?

No

### How is the feature request related to the problem?

NO

### Describe your proposed solution

*Can i download genshin impact although my storage not 150 GB**

### Describe alternatives you've considered

*Can i download genshin impact although my storage not 150 GB because i just have 120 GB in my storage

**Comment by Cryotechnic** [comment]
Because Genshin takes that much space to be installed.  Our launcher can't install files needed for the games to work in non-existing space. This is true for each and every game.

I can't say that you'll have much luck with this, but you can try using: https://github.com/bagusnl/Genshin-MinimalInstaller

This thread is locked.
