### ISSUE TITLE
[Request]: Add "Do not show again" to "Media Feature Pack cannot be found!" for Honkai Impact 3rd

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#301]
### Is your request related to a problem?

No

### Describe your proposed solution

Add a button/selection to not show the `Media Feature Pack cannot be found!` prompt again when launching Honkai Impact 3rd. There could be a checkbox in Collapse's setting which reverts the `Do not show again` setting.

I don't want to keep pressing `Skip` as I haven't had any issues without having the Media Feature Pack installed. 

### Describe alternatives you've considered

Installing the Media Feature Pack, but apparently that doesn't make the message go away on my computer. Either way, I haven't had any issues playing without the pack installed.

**Comment by bagusnl** [comment]
Hi~ Thanks for submitting enhancement feedback for Collapse!

The fix is up in the main branch, but it will take a bit until it releases into Preview branch and eventually into Stable. Though, if you want to try it, you can go to this workflow run (https://github.com/CollapseLauncher/Collapse/actions/runs/6608244797) and once it's done you can download its artifact. You can apply it by simply overwriting your current Collapse preview branch installation in `app-1.72.5` folder with the contents of that run's artifact.
