### ISSUE TITLE
[Tracking:] Zenless Zone Zero (ZZZ) support

### ISSUE THREAD

**Issue by golfista** [CollapseLauncher/Collapse#313]
### Is your request related to a problem?

No

### Describe your proposed solution

Since people have access to the beta, it would be cool to be able to download ZZZ from Collapse

### Describe alternatives you've considered

Default launcher

**Comment by bagusnl** [comment]
Thank you for submitting feature request for Collapse!

Due to the nature of ZZZ's current Equalizing test being a "Closed Beta" we can't really provide any support for it, though shall internal team have different opinion we will send an update in this thread.

In the meantime, we'll use this thread as ZZZ support tracking so no need to close this issue

**Comment by da3dsoul1** [comment]
Looking forward to ZZZ support when it's released!

**Comment by neon-nyan** [comment]
We are currently working on it!
Tracking PR: #511

**Comment by neon-nyan** [comment]
Closing the issue as we have implemented the support starting from v1.80.14 release.
See you soon in New Eridu, Proxies!
