### ISSUE TITLE
[Request]: Suggest adding support for game controllers.

### ISSUE THREAD

**Issue by Eroufs** [CollapseLauncher/Collapse#375]
### Is your request related to a problem?

No

### Describe your proposed solution

I hope to use the game controller to operate Collapse.

### Describe alternatives you've considered

no

**Comment by bagusnl** [comment]
Heyyo~
Thank you for submitting an enhancement request for Collapse!

As far as the feature requested goes, I'm not sure how useful it could be. Reason being, hoyo games despite having controller input support, still needs M&K input on PC due to not having on-screen kb input. Worst one, in Genshin controller input is disabled until you go past the door menu.

What do you think @gablm ?

**Comment by gablm** [comment]
Hello!

Even though the ability of navigating using a controller would be a nice feature, I don't believe it is feasible to implement right now. The WinAppSdk version of WinUI3 does not seem to have out of box support for navigating and interacting with the UI with gamepads like the UWP version does. [Source](https://github.com/microsoft/microsoft-ui-xaml/issues/6891)

That said, a possible implementation would be using [Windows.Gaming.Input.Gamepad](https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad) to continuously loop over the current controller state and convert the Gamepad input to Keyboard input. The problem with this is that it would require a massive overhaul to the UI, in order to add XYFocusNavigation to most elements, as Collapse also doesn't fully support keyboard navigation.

**Comment by bagusnl** [comment]
Thanks for the insight @gablm !

Due to this complicity of the feature and the minimal use case. I don't think we will add support to use Controller in Collapse directly. Alternative that you can use is apps that can rebind your controller input to mouse and keyboard input like joy2key https://joytokey.net/en/

We are sorry if this not the outcome you have expected, again, thank you for your support <3!
