### ISSUE TITLE
[Request]: Download speed limit

### ISSUE THREAD

**Issue by Bruxes** [CollapseLauncher/Collapse#394]
### Is your request related to a problem?

Yes

### Describe your proposed solution

I would like to have a speed limiter when downloading packages.

### Describe alternatives you've considered

I would like to have a speed limiter when downloading packages.

**Comment by bagusnl** [comment]
Heyyo~

Thank you for submitting enhancement request for Collapse! As for the request, we were already planned to add this but since we use custom implementation for the download process (using Hi3Helper.HTTP) for features such as multithreaded downloads, implementing a speed limit using something like [ThrottledStream](https://www.codeproject.com/Articles/18243/Bandwidth-throttling) is more involved process than we initially thought.

Though no worries, we can keep this ticket open and see when we can get back into this and will update you when we have anything to put out!

If you need workaround you can use network-based speed limiter such as NetLimiter, though its a paid software unfortunately

**Comment by Cryotechnic** [comment]
Further proposed enhancements, merging from #481, #482:

- Allow for custom timeframes where speed is not limited.
- Execute action/application on task complete (download, update or repair)

**Comment by zakidze** [comment]
hello where to limit and planify donwload speed? i dont see any button on that im on version 1.80.19
