### ISSUE TITLE
[BUG]: Pre-installation cannot detect update packages for 2 past versions.

### ISSUE THREAD

**Issue by minhngoc25a** [CollapseLauncher/Collapse#439]
### Is your request related to a problem?

No

### Describe your proposed solution

Along with one version update (e.g., 1.5 to 1.6), for some games, Hoyoverse also provides a two-version update pack (e.g., 1.4 to 1.6). Currently, if the new version is ahead of the locally installed version for two updates, Collapse would download the entire game again.

### Describe alternatives you've considered

This doesn't have any alternatives.

### Additional context

If you guys want to test this out, find a source that archives old versions of Hoyoverse's game, then download that source, extract the archive to the local hard drive so that it matches the directory structure of the game, and then test the two-version jump on the official launcher.

**Comment by neon-nyan** [comment]
Hi @minhngoc25a,

Thank you for reporting this issue.
The launcher should've supported this mechanism for long time ago but seems like it's regressing due to changes have been made.
We will investigate it and try to replicate the issue at our end but due to Real-life activities of our core maintainers, there might be delays for the investigation to be done.

**Comment by neon-nyan** [comment]
Also, can you please specify what game that have this specific issue?

**Comment by minhngoc25a** [comment]
I had this issue with Honkai: Star Rail. It seems like if the previous version was updated by the official launcher, then Collapse would somehow be unable to detect this and download the game from scratch. I returned to Honkai: Star Rail after two versions on the Collapse launcher.

**Comment by neon-nyan** [comment]
> I had this issue with Honkai: Star Rail. It seems like if the previous version was updated by the official launcher, then Collapse would somehow be unable to detect this and download the game from scratch. I returned to Honkai: Star Rail after two versions on the Collapse launcher.

Very sorry for the late update on this.
Based on what the API provides, it only includes only 1 version behind for the diff.
<img width="688" alt="image" src="https://github.com/CollapseLauncher/Collapse/assets/30566970/32ff0597-25a2-42b8-9343-1fc64aea3d62">

Unfortunately, as we don't have control over HoYoverse's API, this issue is out of scope of our launcher.
FYI that this should work for other game (like Genshin) as they provides 3 diffs version behind.

Closing this issue for now and thank you for using Collapse Launcher!
