### ISSUE TITLE
[Notice]: Users' preloading after HSR 2.1 may encounter PCDN provision files

### ISSUE THREAD

**Issue by LaoshuBaby** [CollapseLauncher/Collapse#440]
### Is your request related to a problem?

No

### Describe your proposed solution

https://github.com/Scighost/Starward/issues/738

### Describe alternatives you've considered

<small>这并不算是一个Bug report或者具体的Feature请求，只是一项记录，因为Collapse和Starward同样都是第三方启动器，因此可能一样会有位于中国大陆的用户遇到此问题，并且龟速下载甚至断线。这是为了避免有用户认为这是Collapse启动器的问题。</small>

This is not a bug report or a specific Feature request, just a record. Because Collapse and Starward are both third-party launchers, there may also be users inside China who encounter this problem and downloads slowly or even disconnections. This issue is to avoid users thinking this is a problem with the Collapse launcher.

**Comment by bagusnl** [comment]
Thank you for telling us there is an issue within hoyo's CDN.
Can someone make an announcement about it in Chinese?
Just title and short summary of the issue should do


For those who came by this thread, we have published a delta patch uploaded on GoFile and MediaFire. Announcement about delta usually only happen in the discord server but here is the copy of it:

***

# HSR 2.1 Preload is Available! Delta Patch is also Available!

Hello Trailblazers!  
Preload for Honkai: Star Rail 2.1.0 is available, the regular update file size is about 10GB.
The patch will be live on about March 27, 2024 6:00 AM while the server opened a few hours after.

If you would like to try the delta patch using Collapse, the size for the update is about 2.5GB + 450-500MB/audio language.
PS. The audio package will be downloaded automatically upon patch is live, but if you want to download it beforehand, I have provided the link below:

## Download links for Delta
 
### Global

Main Game Delta:
- GoFile: https://gofile.io/d/Dg0Kcp
- MediaFire: https://www.mediafire.com/file/v28qntk0akmvzls/SRGlb_2.0.0_2.1.0_zstd_crc32_58EE8C21D8D274440D356239736A7790.patch/file

Audio patch file:
- English: https://autopatchos.starrails.com/client/hkrpg_global/35/en-us_2.0.0_2.1.0_hdiff_H9An1j0dDBS4MXzZ.zip
- Japanese: https://autopatchos.starrails.com/client/hkrpg_global/35/ja-jp_2.0.0_2.1.0_hdiff_m4tcYvbVFShTAyKM.zip
- Chinese (zh-cn) : https://autopatchos.starrails.com/client/hkrpg_global/35/zh-cn_2.0.0_2.1.0_hdiff_eaKXmEoGYjADIQwP.zip
- Chinese (zh-tw): https://autopatchos.starrails.com/client/hkrpg_global/35/zh-tw_2.0.0_2.1.0_hdiff_oBEvD0mikIOdqMK8.zip
- Korean : https://autopatchos.starrails.com/client/hkrpg_global/35/ko-kr_2.0.0_2.1.0_hdiff_pzIKMLf3JkQiaUYt.zip


### Mainland China

Main Game Delta:
- GoFile: https://gofile.io/d/zLPDOn
- MediaFire: https://www.mediafire.com/file/53hj4usxz5jnz2z/SRCN_2.0.0_2.1.0_zstd_crc32_1ED4F00BB7BA4B8327E4B24C661D81C2.patch/file

Audio patch file:
- English: https://autopatchcn.bhsr.com/client/hkrpg_cn/33/en-us_2.0.0_2.1.0_hdiff_MK2tnjZE1xPb90Le.zip
- Japanese: https://autopatchcn.bhsr.com/client/hkrpg_cn/33/ja-jp_2.0.0_2.1.0_hdiff_MaToxcp6VgdzW7sn.zip
- Chinese (zh-cn): https://autopatchcn.bhsr.com/client/hkrpg_cn/33/zh-cn_2.0.0_2.1.0_hdiff_tsNrHUifmELWAxn0.zip
- Chinese (zh-tw): https://autopatchcn.bhsr.com/client/hkrpg_cn/33/zh-tw_2.0.0_2.1.0_hdiff_K38ZCQnmXBjaDOgx.zip>
- Korean: https://autopatchcn.bhsr.com/client/hkrpg_cn/33/ko-kr_2.0.0_2.1.0_hdiff_DOI64wNZX3rStxcE.zip
PS: Bilibili delta is unavailable


## Notes regarding repair and cache update availability
Due to the nature on how Honkai: Star Rail updates, we will need to update Collapse Launcher for repair and cache to function. This might take a few hours due to the update happen in work hours where majority of our devs that maintain the repair code lives. We are sorry for the inconvenience. 
Update with the zip and delta is not affected by this. Shall any issue happens, please report in Discord or in GitHub issue ticket.

Hope you guys enjoy the new update once its live!
Thank you for your support

**Comment by LaoshuBaby** [comment]
> For those who came by this thread, we have published a delta patch uploaded on GoFile and MediaFire. Announcement about delta usually only happen in the discord server but here is the copy of it:

# 给中国大陆用户 For Mainland of China user

对于因为种种原因点到这个Issue帖子的朋友，我们发布了一个上传在GoFile和MediaFire上的增量补丁。关于增量补丁的公告通常仅发布在Discord上，不过我们复制到了这里一份。

如果您遇到了使用启动器预加载或正式更新过程中极为缓慢或反复断线的问题，可以尝试更换网络环境，这并不是启动器的技术错误造成的。

**Comment by LaoshuBaby** [comment]
> Audio patch file:

The problem is mainly because this link, "https://autopatchcn.bhsr.com", after this round of preloading started, added a lot of CDNs that may not be of satisfactory quality, some of which exist in the form of PCDN

The following is the cname obtained by accessing and performing DNS resolution from different regions in China

#### autopatchcn.yuanshen.com
* autopatchcn-yuanshen-com-idvmgra.qiniudns.com
* autopatchcn.yuanshen.com.volcgslb.com
* autopatchcn.yuanshen.com.wsdvs.com
* autopatchcn.yuanshen.com.cdn.dnsv1.com
* autopatchcn.yuanshen.com.w.kunlungr.com
#### autopatchcn.bhsr.com
* autopatchcn.bhsr.com.cdn.dnsv1.com.cn
* autopatchcn.bhsr.com.cdn20.com
* autopatchcn.bhsr.com.w.cdngslb.com
* autopatchcn.bhsr.com.volcgslb.com
* autopatchcn-bhsr-com-idvmejs.qiniudns.com

**Comment by bagusnl** [comment]
I see, thank you for the insight. If you think there is the need for a mirror, I think for the audio patches itself we can lend a hand. 

Unsure about the hdiff zip as its pretty big. At most I can reupload them to GoFiles which since I dont have the budget for premium, gonna expire within a few days.

**Comment by LaoshuBaby** [comment]
> At most I can reupload them to GoFiles which since I dont have the budget for premium, gonna expire within a few days.

That seems really unnecessary, because for players inside China, GoFiles/MEGA/Others file services is an overseas website and may be slower than a bad CDN or even blocked by the GFW.

~~Maybe only can wish for good luck while the DNS resolution processing~~

**Comment by bagusnl** [comment]
Got it, thanks!

I currently dont have access to my laptop so it might take a few hours for me to post the notification announcement.

Cc @CollapseLauncher/core-maintainers feel free to post the notification if you guys have a time. Only the CN one above should do as it only appears to affect Mainland China and Bilibili region

**Comment by LaoshuBaby** [comment]
![Performance Art](https://github.com/CollapseLauncher/Collapse/assets/42690037/08a103dc-4bbd-443e-b445-dc11016f18a8)
https://github.com/Scighost/Starward/issues/738#issuecomment-2068436813

~~Repeating screenshots is a performance art~~

According to detection by developers in mainland China, PCDN is no longer used in the preloading of Genshin Impact 4.6 starting today. However, the speed may still be very slow due to excessive pressure on the CDN service provider. It is recommended to download during off-peak hours.

(Issue can be closed)

--

据中国大陆的开发者检测，在今天开始的原神4.6的预加载中，已经不再使用PCDN了，但是可能因为CDN服务商压力过大导致速度依然很慢，建议错峰下载

（Issue可关闭）
