### ISSUE TITLE
[Bug]: Tray icon does not appear in full install

### ISSUE THREAD

**Issue by bluebudg-e** [CollapseLauncher/Collapse#478]
### Affected Version

1.73.8 (full install)

### Bug Behavior

Minimizing the program does not cause the tray icon to appear, so the program has to be closed through the task manager if it has to be used again.
Compared to the portable version, it does not appear even when starting the program.

### Expected Behavior

The tray icon in the portable version is always present in the system tray.

### Steps to reproduce

Installing and running the 'full install' version of Collapse.

### Screenshot(s)

- Tray not appearing
![2024-06-07_12-39-PM](https://github.com/CollapseLauncher/Collapse/assets/36739579/df10a86b-e374-4ad3-bad2-b528d9dba7e6)
- Video comparison ('CL' is the portable version)
https://youtu.be/ef1A2E9eYPs
- File locations
https://github.com/CollapseLauncher/Collapse/assets/36739579/8cf6a942-91aa-451b-bb3d-136fa5045cec

### Additional Information

One note: the UAC popup for the 'full install' executable does not say that it is signed

**Comment by bluebudg-e** [comment]
new update yay
uninstalled the old version but my dummy head uninstalled the full game
all problems seem to be gone now (on the full install)

**Comment by bagusnl** [comment]
Update on this one, we will be migrated to MSI installer which SignPath would be able to sign both the MSI and the contents inside of it instead of the current implementation which only able to sign the installer itself.

The commit is on https://github.com/CollapseLauncher/Collapse/commit/b3a0c6feffa54cecefc1c0f5bc8fadf3551e60ca but currently reverted as we are still not ready with the other implementation such as the uninstall method that might break after an update
