### ISSUE TITLE
[Request]: Extract then delete

### ISSUE THREAD

**Issue by NSPC911** [CollapseLauncher/Collapse#523]
### Is your request related to a problem?

No

### Describe your proposed solution

Okay, so something I noticed with the official launcher is that you need 2x the download size for extracting the archives.
Collapse Launcher does the same and stores them as `.zip.00x.xxxxxx` in the game files.
Is it possible for it to extract one archive, delete the archive, then continue with the next one?

Honkai: Star Rail uses 2 archives, so taking the one that is larger and adding to the minimum disk size should be good enough.
Zenless Zone Zero uses 10 archives, so, again, taking the one that is the largest and adding to the minimum disk size should be good enough. This reduces the minimum disk size from 110GB to just about 60GB.

### Describe alternatives you've considered

NIL, no alternatives other than to not implement it.

**Comment by bagusnl** [comment]
The thing with the segmented archive is that it is hard to predict when the extraction phase needs the other segment for a file. You can try it by only opening a merged 001 chunk and the 7z will say that the archive is corrupted.

But not to be afraid, easier (by storage requirements) download mechanism is planned to download all the files individually. But since currently, the API doesn't serve Zenless game files as individual extracted files then it's not possible to make the method for it (same reason Repair function is not there).

**Comment by NSPC911** [comment]
Yep, tried opening the archive with 7z and it says it is corrupted. Is it possible for Honkai: Star Rail then?

**Comment by bagusnl** [comment]
For HSR its planned to have more storage friendly soon if they refuse to use sophon chunked download system as I said previously
