### ISSUE TITLE
[Bug]: Game repair and Cache update still not available

### ISSUE THREAD

**Issue by Caelum008** [CollapseLauncher/Collapse#595]
### Affected Version

1.81.6-Pre

### Bug Behavior

This appears when trying to update cache and game repair:
`System.IO.InvalidDataException: The dispatcher response is invalid! Please open an issue to our GitHub page to report this issue.
   at CollapseLauncher.StarRailCache.Fetch(CancellationToken token)
   at CollapseLauncher.StarRailCache.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`1.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailCache.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.CachesPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)`

### Expected Behavior

Should have updated cache.

### Steps to reproduce

1. Restarted Collapse
2. Cleared metadata and restart

**Comment by bagusnl** [comment]
@neon-nyan did we have any change in the branch that has not been upped to preview? 
I can't seem to replicate this last night

**Comment by neon-nyan** [comment]
I think I made a big oopsies here. The public preview and stable releases are current pointing to neon-nyan/CollapseLauncher-ReleaseRepo url for the CDN, Asset Index and Manifest url. Since I was forking the repo with the same name and I forgot to use different one, it refers to my own fork instead and due to it out-of-sync, the metadata change was still not applicable until I just sync the main branch few minutes ago.

**Comment by neon-nyan** [comment]
Synced. Should be fixed now, Can you try it again? @Caelum008
If the issue still persist, please change your CDN from GitHub to GitLab or others at the moment

**Comment by bagusnl** [comment]
Neooooooooooonnnnn

**Comment by Caelum008** [comment]
> Synced. Should be fixed now, Can you try it again? @Caelum008 If the issue still persist, please change your CDN from GitHub to GitLab or others at the moment

ohh. I just got a metadata update. thank you so much! I'm gonna close this now.
