### ISSUE TITLE
[Bug]: Unhandled Error when manually checking for updates in 1.82.0 Preview

### ISSUE THREAD

**Issue by Cactism** [CollapseLauncher/Collapse#599]
### Affected Version

Collapse 1.82.0 Preview

### Bug Behavior

After clicking the "Check for Update" button in Collapse's settings, an error will appear.
![image](https://github.com/user-attachments/assets/1b26056e-da92-4437-8e69-6170a02c9989)

### Expected Behavior

Collapse should be able to check for updates, like in the latest stable build
![image](https://github.com/user-attachments/assets/54e3e067-4b34-4d7b-bbd8-3fb068c72db8)

### Steps to reproduce

1. While using 1.82.0 Preview, open Collapse's settings panel
2. Check for updates

### Additional Information

I've already tried using a fresh installation of the Preview build, with the same error.

**Comment by neon-nyan** [comment]
Thank you for reporting this bug.
Seems like the Update status returns a null when an update is not available, but somehow we forgot to handle or show an "Up-to-date" message when no update is available.

Should be fixed in the next preview/later stable release and it shouldn't affect update mechanism once a new update is coming.

**Comment by bagusnl** [comment]
Fixed in https://github.com/CollapseLauncher/Collapse/commit/b4b883282ca12e2344710bad8ef502e323560160

**Comment by bagusnl** [comment]
Fix pushed to 1.82.1
Thanks for reporting the issue
